name = "EasyJobRecipes"
uuid = "6e923fd6-89f4-4f43-89cd-c72d1fbcfffd"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
